services:
  web:
    build: .
    container_name: portfolio_web
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_PATH=/app/data/db.sqlite3
    volumes:
      - sqlite_data:/app/data
      - media_data:/app/media
      - static_data:/app/staticfiles
    networks:
      - default
      - npm
    expose:
      - "8000"

networks:
  default:
  npm:
    name: docker_default
    external: true

volumes:
  sqlite_data:
  media_data:
  static_data:
