# Generated by Django 3.0.6 on 2020-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(blank=True)),
                ('from_email', models.CharField(max_length=250)),
            ],
        ),
    ]
